# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ARDesigner' do
  project 'ARDesigner'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARDesigner
  pod 'Google/SignIn'
  pod 'GoogleAPIClientForREST/Drive'
  pod 'ZIPFoundation', '~> 0.9'

end
